services:
  postgres:
    image: postgres:16
    container_name: studycast-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: studycast
      POSTGRES_PASSWORD: localdevpassword
      POSTGRES_DB: studycast
    ports:
     - "5432:5432"
    volumes:
     - studycast_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: studycast-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - studycast_redisdata:/data
volumes:
  studycast_pgdata:
  studycast_redisdata: