import { Link } from "react-router-dom";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="min-h-screen">
      <nav className="flex items-center px-6 py-4 max-w-3xl mx-auto">
        <Link to="/">
          <span className="text-xl font-bold font-['Space_Grotesk'] tracking-tight">
            StudyCast<span className="text-primary">AI</span>
          </span>
        </Link>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-8">
        <Link to="/">
          <Button variant="ghost" size="sm" className="gap-2 mb-6">
            <ArrowLeft className="h-4 w-4" /> Back to home
          </Button>
        </Link>

        <Card>
          <CardContent className="pt-8 pb-10 px-8 space-y-8">
            <div>
              <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
              <p className="text-sm text-muted-foreground">Last updated: June 26, 2026</p>
            </div>

            <p className="text-muted-foreground leading-relaxed">
              By using StudyCast AI ("the app"), you agree to these Terms of Service. If you do
              not agree, please do not use the app.
            </p>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold">Description of Service</h2>
              <p className="text-muted-foreground leading-relaxed">
                StudyCast AI converts study materials (documents, videos, and YouTube content)
                into audio summaries using AI-generated scripts and text-to-speech technology.
                The app also provides AI-generated answers to questions about your uploaded
                materials.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold">Account Registration</h2>
              <p className="text-muted-foreground leading-relaxed">
                You must provide a valid email address to create an account. You are responsible
                for maintaining the confidentiality of your password and for all activity that
                occurs under your account.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold">Acceptable Use</h2>
              <p className="text-muted-foreground leading-relaxed">You agree not to:</p>
              <ul className="list-disc list-inside text-muted-foreground space-y-1">
                <li>Upload content you do not have the legal right to use</li>
                <li>Upload copyrighted material without authorization, where such use would violate the rights of the copyright holder</li>
                <li>Use the app to generate content that is illegal, harmful, or violates the rights of others</li>
                <li>Attempt to circumvent free-tier usage limits through automated means or multiple accounts</li>
                <li>Use the app in any way that could damage, disable, or impair our infrastructure or third-party services we rely on</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold">YouTube Content</h2>
              <p className="text-muted-foreground leading-relaxed">
                When you submit a YouTube URL, we attempt to retrieve publicly available
                caption/transcript data associated with that video for the purpose of generating
                audio content. This feature depends on captions being available and may be
                temporarily unavailable due to factors outside our control, including
                restrictions imposed by YouTube.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold">AI-Generated Content</h2>
              <p className="text-muted-foreground leading-relaxed">
                Content generated by the app (scripts, audio, and answers to questions) is
                produced using third-party AI services and may contain inaccuracies. You should
                not rely on AI-generated content as a substitute for verified, authoritative
                sources, especially for academic, medical, legal, or safety-critical purposes.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold">Free Tier Limits</h2>
              <p className="text-muted-foreground leading-relaxed">
                The app provides a limited number of free generations per day. We reserve the
                right to change these limits at any time.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold">Intellectual Property</h2>
              <p className="text-muted-foreground leading-relaxed">
                You retain ownership of the materials you upload. By uploading content, you
                grant us a limited license to process that content solely for the purpose of
                providing the service to you. We do not claim ownership over your uploaded
                materials or the content generated from them.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold">Disclaimer of Warranties</h2>
              <p className="text-muted-foreground leading-relaxed">
                The app is provided "as is" without warranties of any kind, express or implied.
                We do not guarantee that the service will be uninterrupted, error-free, or that
                AI-generated content will be accurate or complete.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold">Limitation of Liability</h2>
              <p className="text-muted-foreground leading-relaxed">
                To the fullest extent permitted by law, we shall not be liable for any indirect,
                incidental, or consequential damages arising from your use of the app.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold">Termination</h2>
              <p className="text-muted-foreground leading-relaxed">
                We reserve the right to suspend or terminate accounts that violate these Terms of
                Service.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold">Changes to These Terms</h2>
              <p className="text-muted-foreground leading-relaxed">
                We may update these Terms of Service from time to time. Continued use of the app
                after changes are posted constitutes acceptance of the updated terms.
              </p>
            </section>

            <section className="space-y-3 pt-4 border-t border-border">
              <h2 className="text-xl font-semibold">Contact Us</h2>
              <p className="text-muted-foreground leading-relaxed">
                If you have questions about these Terms of Service, contact us at:{" "}
                <a href="mailto:testemail07077@gmail.com" className="text-primary hover:underline">
                  testemail07077@gmail.com
                </a>
              </p>
            </section>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}