import { Link } from "react-router-dom";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <nav className="px-6 py-4 max-w-3xl mx-auto">
        <Link to="/" className="text-xl font-bold font-['Space_Grotesk'] tracking-tight">
          StudyCast<span className="text-primary">AI</span>
        </Link>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-8 prose prose-neutral dark:prose-invert">
        <h1>Terms of Service</h1>
        <p className="text-muted-foreground">Last updated: June 26, 2026</p>

        <p>
          By using StudyCast AI ("the app"), you agree to these Terms of Service. If you do not
          agree, please do not use the app.
        </p>

        <h2>Description of Service</h2>
        <p>
          StudyCast AI converts study materials (documents, videos, and YouTube content) into audio
          summaries using AI-generated scripts and text-to-speech technology. The app also provides
          AI-generated answers to questions about your uploaded materials.
        </p>

        <h2>Account Registration</h2>
        <p>
          You must provide a valid email address to create an account. You are responsible for
          maintaining the confidentiality of your password and for all activity that occurs under
          your account.
        </p>

        <h2>Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Upload content you do not have the legal right to use</li>
          <li>
            Upload copyrighted material without authorization, where such use would violate the
            rights of the copyright holder
          </li>
          <li>Use the app to generate content that is illegal, harmful, or violates the rights of others</li>
          <li>
            Attempt to circumvent free-tier usage limits through automated means or multiple
            accounts
          </li>
          <li>
            Use the app in any way that could damage, disable, or impair our infrastructure or
            third-party services we rely on
          </li>
        </ul>

        <h2>YouTube Content</h2>
        <p>
          When you submit a YouTube URL, we attempt to retrieve publicly available
          caption/transcript data associated with that video for the purpose of generating audio
          content. This feature depends on captions being available and may be temporarily
          unavailable due to factors outside our control, including restrictions imposed by YouTube.
        </p>

        <h2>AI-Generated Content</h2>
        <p>
          Content generated by the app (scripts, audio, and answers to questions) is produced using
          third-party AI services and may contain inaccuracies. You should not rely on AI-generated
          content as a substitute for verified, authoritative sources, especially for academic,
          medical, legal, or safety-critical purposes.
        </p>

        <h2>Free Tier Limits</h2>
        <p>
          The app provides a limited number of free generations per day. We reserve the right to
          change these limits at any time.
        </p>

        <h2>Intellectual Property</h2>
        <p>
          You retain ownership of the materials you upload. By uploading content, you grant us a
          limited license to process that content solely for the purpose of providing the service to
          you. We do not claim ownership over your uploaded materials or the content generated from
          them.
        </p>

        <h2>Disclaimer of Warranties</h2>
        <p>
          The app is provided "as is" without warranties of any kind, express or implied. We do not
          guarantee that the service will be uninterrupted, error-free, or that AI-generated content
          will be accurate or complete.
        </p>

        <h2>Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by law, we shall not be liable for any indirect,
          incidental, or consequential damages arising from your use of the app.
        </p>

        <h2>Termination</h2>
        <p>
          We reserve the right to suspend or terminate accounts that violate these Terms of Service.
        </p>

        <h2>Changes to These Terms</h2>
        <p>
          We may update these Terms of Service from time to time. Continued use of the app after
          changes are posted constitutes acceptance of the updated terms.
        </p>

        <h2>Contact Us</h2>
        <p>
          If you have questions about these Terms of Service, contact us at:{" "}
          <a href="mailto:cheongjie05@gmail.com">cheongjie05@gmail.com</a>
        </p>
      </main>
    </div>
  );
}
